services:
  - type: web
    name: resourcehub-backend
    env: docker
    repo: https://github.com/hruthik808/ResourceHub
    branch: main
    rootDir: backend/student-resource-reuse
    dockerfilePath: ./backend/student-resource-reuse/Dockerfile