services:
  - type: web
    name: resourcehub-backend
    env: java
    rootDir: backend/student-resource-reuse
    buildCommand: "chmod +x mvnw && ./mvnw clean install"
    startCommand: "java -jar target/*.jar"